const INIT_VILLAGES = 'INIT_VILLAGES';
const MAKE_ORDER = 'MAKE_ORDER';
const SEND_VILLAGER = 'SEND_VILLAGER';
const CALCULATE_SCORES = 'CALCULATE_SCORES';

export {
  INIT_VILLAGES,
  MAKE_ORDER,
  SEND_VILLAGER,
  CALCULATE_SCORES,
};